services:



  app:
    image: dumindaw/simple-library:1.0.0
    depends_on:
      db:
       condition: service_healthy
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DATASOURCE_URL: jdbc:postgresql://db:5432/simple_library
      DATASOURCE_USERNAME: libUser
      DATASOURCE_PASSWORD: pw789
      LOG_LEVEL: DEBUG
    healthcheck:
      test: ["CMD-SHELL", "curl --fail --silent localhost:8081/actuator/health | grep UP || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 20s
    ports:
      - 8081:8081


  db:
    image: postgres:18.1
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: libUser
      POSTGRES_PASSWORD: pw789
      POSTGRES_DB: simple_library
    healthcheck:
       test: ["CMD-SHELL", "pg_isready -U libUser -d simple_library"]
       interval: 10s
       timeout: 5s
       retries: 5
    ports:
      - 5432:5432