spring:
  application:
    name: simple library application
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/simple_library
    username: libUser
    password: pw789
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
