apiVersion: v1
kind: ConfigMap
metadata:
  namespace: simple-library
  name: simple-library-configs
data:
  LOG_LEVEL: DEBUG
  DATASOURCE_URL: jdbc:postgresql://db:5432/simple_library
  DATASOURCE_USERNAME: libUser
